### ISSUE TITLE
ARES crashes

### ISSUE THREAD

**Issue by DanielAndreasen** [DanielAndreasen/MOOGme#17]
Sometimes ARES crashes, and we don't really do anything about it, and just let it crash with a reference to `logARES.txt`. The typical solution is to remove the last line it tried fit. Maybe this can be done automatically and logged/printed to terminal/GUI.

**Comment by gdcteixeira** [comment]
I this is related with a ARES problem that I've encountered before. Sometimes spectra that has been "stitched" together, for example joining the blue and red arms, will have a gap.
This in itself wouldn't normally be a problem but in those gaps it can happen that there is a negative flux value(due to the reduction and rest of pipeline methods).

I think your approach might be worth looking into. 
Something like:
-make a tmp file or load a variable by reading the initial linelist
-make a cycle that will only exit if ARES is successful
-if not successful, use the output to remove the line that made it crash and update the tmp linelist or variable
-Exit the cycle when successful
- log the final linelist used

**Comment by DanielAndreasen** [comment]
That can be a reason, but I also have examples where everything seems fine around the line (the spectra is well reduced), and ARES still fails.
We can make a `force finish` option (default: off) in the ARES driver, which removes bad lines until ARES doesn't crash. I say that, because I'm tired of doing it manually :)

**Comment by DanielAndreasen** [comment]
With commit 963573f it is now possible to remove these lines automatically. When they are removed, the linelist is stored in a temporary file, until there are no more troublesome lines. The temporary files are removed at the end. And this commit does not affect any line lists stored in `rawLinelist`.
Can you take a look @gdcteixeira?

**Comment by gdcteixeira** [comment]
@DanielAndreasen it looks good. 
But I'll put it through some more cases that I know are problematic just to make sure.
I have some with multiple bad lines that I will test.

**Comment by DanielAndreasen** [comment]
If you want, you can also send me the spectra, then I can test it right away.
Also, the input line list needs to be in the right format. Do you have that?

**Comment by DanielAndreasen** [comment]
Did you have time to test this @gdcteixeira ?

**Comment by DanielAndreasen** [comment]
This has been tested now on many spectra with great results.
