### ISSUE TITLE
ewDriver

### ISSUE THREAD

**Issue by MariaTsantaki** [DanielAndreasen/MOOGme#28]
Every iteration I get this warning:

    sh: \rm: command not found

We do not use this command in any function for this driver. Do you have any idea of what this is? 
e.g.:

    sh: \rm: command not found
     i    Teff    logg    [Fe/H]    vt    EPslope    RWslope    |FeI-FeII|
    ----------------------------------------------------------------------
    sh: \rm: command not found
       1  5769    4.47    +0.01    0.99   -0.005     -0.025       0.02
    sh: \rm: command not found

**Comment by DanielAndreasen** [comment]
Hi Maria,

The problem is not MOOGme, but in MOOG. Open the file `Begin.f` and find the line containing `\rm` and change it to `rm`. I think it is line 55. After that, recompile MOOG with `make -f Makefile.xxx`. You might need to clear the directory first with: `make -f Makefile.xxx clean`.
Be sure to open a new terminal before testing it with MOOGme. Let me know if it works.
