### ISSUE TITLE
refine option

### ISSUE THREAD

**Issue by MariaTsantaki** [DanielAndreasen/MOOGme#31]
When is it optimal to use the refine option?

**Comment by DanielAndreasen** [comment]
At the very end. If you have outliers and you remove them, then after all the outliers are removed. Then you simply refine the parameters a bit, based on the previous best solution.

Another thing: We could change how the convergence criteria is set. I just manually put very low (0.001) criteria. It has worked so far with (most of the times) with the stars I've tested, but we could make it a scaling of the original set convergence criteria.

**Comment by MariaTsantaki** [comment]
Could this be part of the refine option? E.g. if there is no convergence, criteria are loosen.

**Comment by DanielAndreasen** [comment]
I'm not a fan of that. If a line list does not converge, then relaxing the convergence criteria does not seem like the way to go. Rather the user should figure out why convergence was not met. It is quite rare that the minimization doesn't work.
When it doesn't work, it is usually because of limitation in the used line list (e.g. too high/low temperature).
